source 'http://rubygems.org'

gem 'rails', '3.2.13'

gem 'rake', '0.8.7'
gem 'bson_ext', '1.6.2'
gem 'mongo', '1.6.2'
gem 'mongoid', '2.4.12'
gem 'mongoid-paperclip', :require => 'mongoid_paperclip'
gem 'paperclip', '3.0.2'
gem 'daemons'
gem 'haml-rails'
gem 'devise'
gem 'devise-encryptable'
gem 'simple_form'
gem 'kaminari', '0.14.1'
gem 'mongoid_slug', :require => 'mongoid/slug'
gem 'state_machine'
gem 'transitions', :require => %w(transitions active_record/transitions)
gem 'hpricot'
gem 'jonathantron-paypal'
gem 'net-sftp'
gem 'mongoid_session_store'
gem 'rack-raw-upload'
gem 'savon_model'
gem 'prawn', '1.0.0.rc1'
gem 'to_xls'
gem 'barby'
gem 'chunky_png' # required by barby
gem 'oauth'
gem 'delayed_job_mongoid'
gem 'airbrake'
gem 'nested_form'
gem 'bootstrap-datepicker-rails'
gem 'google_drive'
gem 'box-api'
gem 'poppler'
gem 'anjlab-tesseract', :require => 'tesseract'
gem 'unicode_utils'
gem 'axlsx', '1.3.4'
gem 'breadcrumbs_on_rails'
gem 'strong_parameters'
gem 'rabl'
gem 'tire'
gem 'typhoeus'

group :assets do
  gem 'twitter-bootstrap-rails'
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'therubyracer'
  gem 'jquery-ui-rails'
  gem 'backbone-on-rails', '0.9.9.0'
  gem 'backbone-forms-on-rails'
  gem 'compass-rails'
end

gem 'jquery-rails'

group :development, :test do
  gem 'thin'
  gem 'debugger'
  gem 'letter_opener'
  gem 'rspec-rails'
  gem 'quiet_assets'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
end

group :test do
  gem 'mongoid-rspec'
  gem 'factory_girl_rails'
  gem 'simplecov', :require => false
  gem 'capybara'
  gem 'spork', '1.0.0rc3'
  gem 'guard-spork'
  gem 'guard-rspec'
  gem 'database_cleaner'
end
