#!/usr/bin/env ruby
require 'rubygems'
require 'daemons'
require 'yaml'
require 'active_support/core_ext/object'
require 'active_support/core_ext/hash'

file_path = File.dirname(__FILE__) + "/../../config/daemons.yml"
options = YAML.load(File.open(file_path)).with_indifferent_access
options[:dir_mode] = options[:dir_mode].to_sym

Daemons.run File.dirname(__FILE__) + "/manager.rb", options
