defaults: &defaults
  root_url: https://beta.irf-cloud.com/IRFService/services/IRFService.svc
  notify_error_to: emmanuel.pliez@ibizasoftware.fr

test:
  <<: *defaults

development:
  <<: *defaults

sandbox:
  <<: *defaults

staging:
  <<: *defaults

production:
  root_url: https://webservice.irf-cloud.com/IRFService/services/IRFService.svc
  notify_error_to: emmanuel.pliez@ibizasoftware.fr
