defaults: &defaults
  currency: EUR
  business_email: lailol_1312465379_biz@directmada.com
  url: https://www.sandbox.paypal.com/cgi-bin/webscr

development:
  <<: *defaults

sandbox:
  <<: *defaults

staging:
  <<: *defaults

production:
  currency: EUR
  business_email: florent.tachot@grevalis.com
  url: https://www.paypal.com/cgi-bin/webscr
