development:
  currency: EUR
  business_email: lailol_1312465379_biz@directmada.com
  url: https://www.sandbox.paypal.com/cgi-bin/webscr

production:
  currency: EUR
  business_email: lailol_1312465379_biz@directmada.com
  url: https://www.sandbox.paypal.com/cgi-bin/webscr

staging:
  currency: EUR
  business_email: florent.tachot@grevalis.com
  url: https://www.paypal.com/cgi-bin/webscr
