RefreshDashboardStatisticsWorker:
  cron: '*/15 * * * *'

JobOrchestratorWorker:
  cron: '*/10 * * * *'

FtpFetcherWorker:
  cron: '0 * * * *'

RetrieveOcrProcessedDocumentWorker:
  every: '1m'

UpdateAccountingPlanWorker:
  cron: '00 4 * * *'

SynchronizeRetrieverWorker:
  every: '5s'

ProcessRetrievedDataWorker:
  every: '5s'

ProcessOperationsWorker:
  every: '10m'

RemoveOldestRetrievedDataWorker:
  cron: '0 0 * * *'

InitializePeriodsWorker:
  cron: '0 3 1 * *'
