## Miscelaneous workers

RefreshDashboardStatisticsWorker:
  queue: default
  cron: '*/5 * * * *'
CreateInvoicePdfWorker:
  queue: high
  cron: '0 3 1 * *'
InitializePeriodsWorker:
  queue: high
  cron: '0 3 1 * *'
SubscriptionStatisticsWorker:
  queue: default
  cron: '0 5 * * *'
RemindToOrderNewKitWorker:
  queue: default
  cron: '15 3 1 12 *'

## Notifications worker
Notifications::DocumentWorker:
  queue: default
  cron: '0 8 * * *'
Notifications::RetrieversWorker:
  queue: default
  cron: '0 8 * * *'
Notifications::ScansNotDeliveredNotificationWorker:
  queue: high
  cron: '0 1 * * *'
Notifications::PaperQuotaReachedWorker:
  queue: default
  cron: '0 8 * * *'
Notifications::PublishedDocumentDailyWorker:
  queue: default
  cron: '0 8 * * *'
Notifications::PreAssignmentDeliveryDailyWorker:
  queue: default
  cron: '0 8 * * *'
Notifications::PreAssignmentExportWorker:
  queue: default
  cron: '0 8 * * *'
Notifications::ProcessedRequestsWorker:
  queue: default
  cron: '0 8 * * *'



## Accounting Plan worker

AccountingPlan::IbizaUpdateWorker:
  queue: default
  cron: '0 4 * * *'

AccountingPlan::ExactOnlineUpdateWorker:
  queue: default
  cron: '0 4 * * *'



#TO DO : Remove
# ClearCurrencyRateWorker:
#   queue: default
#   cron: '0 1 1 */6 *'

## Budgea retrievers workers

ProcessOperationsWorker:
  queue: default
  cron: '*/10 * * * * *'

## resume budgea retriever connector state
ResumeBudgeaRetrieverWorker:
  queue: default
  cron: '0 */15 * * * *'

# TO DO : Remove
# RemoveOldestRetrievedDataWorker:
#   queue: default
#   cron: '0 0 * * *'

# UpdateConnectorsListWorker:
#   queue: default
#   cron: '45 3 * * *'

## Accounting flow workers

FtpFetcherWorker:
  queue: default
  cron: '*/10 * * * * *'

RetrieveEmailedDocumentWorker:
  queue: default
  cron: '*/10 * * * * *'


## File import

FileImport::DropboxWorker:
  queue: file_import
  cron: '*/10 * * * * *'

FileImport::FtpFromAllWorker:
  queue: file_import
  cron: '0 0 */6 * * *'

FileImport::IbizaboxWorker:
  queue: file_import
  cron: '0 0 */6 * * *'



RetrieveOcrProcessedDocumentWorker:
  queue: default
  cron: '*/10 * * * * *'

SendToGroupingWorker:
  queue: default
  cron: '*/2 * * * * *'

GroupDocumentWorker:
  queue: default
  cron: '*/2 * * * * *'

PublishDocumentWorker:
  queue: high
  cron: '*/2 * * * * *'

SendPieceToPreAssignmentWorker:
  queue: high
  cron: '*/5 * * * * *'

ProcessRetrievedDataWorker:
  queue: high
  cron: '*/2 * * * * *'

RetrievePreAssignmentsWorker:
  queue: high
  cron: '*/10 * * * * *'



## Pre assignment builder & delivery

PreAssignment::Builder::IbizaWorker:
  queue: high
  cron: '*/10 * * * * *'

PreAssignment::Builder::ExactOnlineWorker:
  queue: high
  cron: '*/10 * * * * *'

PreAssignment::Delivery::IbizaWorker:
  queue: high
  cron: '*/10 * * * * *'

PreAssignment::Delivery::ExactOnlineWorker:
  queue: high
  cron: '*/10 * * * * *'




McfProcessorWorker:
  queue: default
  cron: '0 */5 * * * *'

JobProcessorWorker:
  queue: high
  cron: '0 */5 * * * *'

## destroy some data
DatabaseCleanerWorker:
  queue: default
  cron: '0 2 * * *'

## Daily data verifier worker
DataVerificatorWorker:
  queue: default
  cron: '0 3 * * *'

## Zoho CRM sync
ZohoCrmSynchronizerWorker:
  queue: default
  cron: '0 1 1 * *'

## Delivery workers

DeliverFileToDropbox: &deliver_file_defaults
  class: FileDelivery::DeliverFileWorker
  queue: file_delivery
  cron: '*/10 * * * * *'
  args: dbb
DeliverFileToDropboxExtended:
  <<: *deliver_file_defaults
  args: dbx
DeliverFileToBox:
  <<: *deliver_file_defaults
  args: box
DeliverFileToGoogleDrive:
  <<: *deliver_file_defaults
  args: gdr
DeliverFileToFTP:
  <<: *deliver_file_defaults
  args: ftp
DeliverFileToKnowings:
  <<: *deliver_file_defaults
  args: kwg
DeliverFileToMcf:
  <<: *deliver_file_defaults
  args: mcf
