## Miscelaneous workers

RefreshDashboardStatisticsWorker:
  queue: default
  cron: '*/5 * * * *'
CreateInvoicePdfWorker:
  queue: high
  cron: '0 3 1 * *'
InitializePeriodsWorker:
  queue: high
  cron: '0 3 1 * *'
SubscriptionStatisticsWorker:
  queue: default
  cron: '0 5 * * *'
DocumentNotificationWorker:
  queue: default
  cron: '0 8 * * *'
RetrieverNotificationWorker:
  queue: default
  cron: '0 8 * * *'
ScansNotDeliveredNotificationWorker:
  queue: high
  cron: '0 1 * * *'
UpdateAccountingPlanWorker:
  queue: default
  cron: '0 4 * * *'
RemindToOrderNewKitWorker:
  queue: default
  cron: '15 3 1 12 *'
NotifyPaperQuotaReachedWorker:
  queue: default
  cron: '0 8 * * *'
NotifyPublishedDocumentDailyWorker:
  queue: default
  cron: '0 8 * * *'
NotifyPreAssignmentDeliveryFailureDailyWorker:
  queue: default
  cron: '0 8 * * *'
NotifyPreAssignmentExportWorker:
  queue: default
  cron: '0 8 * * *'
ClearCurrencyRateWorker:
  queue: default
  cron: '0 1 1 */6 *'

## Budgea retrievers workers

ProcessOperationsWorker:
  queue: default
  cron: '*/10 * * * * *'
RemoveOldestRetrievedDataWorker:
  queue: default
  cron: '0 0 * * *'
NotifyProcessedRequestsWorker:
  queue: default
  cron: '0 8 * * *'
UpdateConnectorsListWorker:
  queue: default
  cron: '45 3 * * *'

## Accounting flow workers

FtpFetcherWorker:
  queue: default
  cron: '* * * * *'
RetrieveEmailedDocumentWorker:
  queue: default
  cron: '* * * * *'
ImportFromDropboxWorker:
  queue: file_import
  cron: '*/10 * * * * *'
ImportFromAllFTPWorker:
  queue: file_import
  cron: '0 0 */6 * * *'
InitializeIbizaboxImportWorker:
  queue: file_import
  cron: '0 0 */6 * * *'

RetrieveOcrProcessedDocumentWorker:
  queue: high
  cron: '*/10 * * * * *'

JobOrchestratorWorker:
  queue: high
  cron: '*/2 * * * * *'

RetrievePreAssignmentsWorker:
  queue: default
  cron: '*/10 * * * * *'
DeliverPreAssignmentsWorker:
  queue: default
  cron: '*/10 * * * * *'

McfProcessorWorker:
  queue: default
  cron: '0 */5 * * * *'

## Erase records every year (created_at < 2.years.ago
# DatabaseCleanerWorker:
#   queue: default
#   cron: 0 0 1 1 *


## Delivery workers

DeliverFileToDropbox: &deliver_file_defaults
  class: DeliverFileWorker
  queue: file_delivery
  cron: '*/10 * * * * *'
  args: dbb
DeliverFileToDropboxExtended:
  <<: *deliver_file_defaults
  args: dbx
DeliverFileToBox:
  <<: *deliver_file_defaults
  args: box
DeliverFileToGoogleDrive:
  <<: *deliver_file_defaults
  args: gdr
DeliverFileToFTP:
  <<: *deliver_file_defaults
  args: ftp
DeliverFileToKnowings:
  <<: *deliver_file_defaults
  args: kwg
DeliverFileToMcf:
  <<: *deliver_file_defaults
  args: mcf
