RefreshDashboardStatisticsWorker:
  every: '5m'

JobOrchestratorWorker:
  cron: '*/10 * * * *'

FtpFetcherWorker:
  cron: '0 * * * *'

RetrieveOcrProcessedDocumentWorker:
  every: '1m'

CreateInvoicePdfWorker:
  cron: '0 3 1 * *'

SynchronizeRetrieverWorker:
  every: '5s'

ProcessRetrievedDataWorker:
  every: '5s'

RemoveOldestRetrievedDataWorker:
  cron: '0 0 * * *'

InitializePeriodsWorker:
  cron: '0 3 1 * *'
