## Miscelaneous workers

RefreshDashboardStatisticsWorker:
  queue: default
  cron: '*/5 * * * *'
CreateInvoicePdfWorker:
  queue: high
  cron: '0 3 1 * *'
InitializePeriodsWorker:
  queue: high
  cron: '0 3 1 * *'
DocumentNotificationWorker:
  queue: default
  cron: '0 8 * * *'
ScansNotDeliveredNotificationWorker:
  queue: high
  cron: '0 1 * * *'
UpdateAccountingPlanWorker:
  queue: default
  cron: '0 4 * * *'

## Budgea retrievers workers
ProcessOperationsWorker:
  queue: default
  cron: '*/10 * * * * *'
RemoveOldestRetrievedDataWorker:
  queue: default
  cron: '0 0 * * *'
NotifyProcessedRequestsWorker:
  queue: default
  cron: '0 8 * * *'

## Accounting flow workers

FtpFetcherWorker:
  queue: default
  cron: '* * * * *'
RetrieveEmailedDocumentWorker:
  queue: default
  cron: '* * * * *'
ImportFromDropboxWorker:
  queue: default
  cron: '*/10 * * * * *'

RetrieveOcrProcessedDocumentWorker:
  queue: high
  cron: '*/10 * * * * *'

JobOrchestratorWorker:
  queue: high
  cron: '*/2 * * * * *'

RetrievePreAssignmentsWorker:
  queue: default
  cron: '*/10 * * * * *'
DeliverPreAssignmentsWorker:
  queue: default
  cron: '*/10 * * * * *'

## Delivery workers

DeliverFileToDropbox: &deliver_file_defaults
  class: DeliverFileWorker
  queue: file_delivery
  cron: '*/10 * * * * *'
  args: dbb
DeliverFileToDropboxExtended:
  <<: *deliver_file_defaults
  args: dbx
DeliverFileToBox:
  <<: *deliver_file_defaults
  args: box
DeliverFileToGoogleDrive:
  <<: *deliver_file_defaults
  args: gdr
DeliverFileToFTP:
  <<: *deliver_file_defaults
  args: ftp
DeliverFileToKnowings:
  <<: *deliver_file_defaults
  args: kwg
