RefreshDashboardStatisticsWorker:
  every: '5m'

JobOrchestratorWorker:
  cron: '*/10 * * * *'

FtpFetcherWorker:
  cron: '0 * * * *'

RetrieveOcrProcessedDocumentWorker:
  every: '1m'

UpdateAccountingPlanWorker:
  cron: '00 4 * * *'

CreateInvoicePdfWorker:
  cron: '0 3 1 * *'

SynchronizeRetrieverWorker:
  every: '5s'

ProcessRetrievedDataWorker:
  every: '5s'

ProcessOperationsWorker:
  every: '1m'

RemoveOldestRetrievedDataWorker:
  cron: '0 0 * * *'

NotifyProcessedRequestsWorker:
  cron: '0 8 * * *'

InitializePeriodsWorker:
  cron: '0 3 1 * *'

DocumentNotificationWorker:
  cron: '0 8 * * *'

ScansNotDeliveredNotificationWorker:
  cron: '0 1 * * *'

FileDeliveryWorker:
  every: '1m'

ImportFromDropboxWorker:
  every: '1m'
