RefreshDashboardStatisticsWorker:
  cron: '*/15 * * * *'

JobOrchestratorWorker:
  cron: '*/10 * * * *'

FtpFetcherWorker:
  cron: '0 * * * *'

UpdateAccountingPlanWorker:
  cron: '00 4 * * *'

CreateInvoicePdfWorker:
  cron: '0 3 1 * *'
