defaults: &defaults
  secret_key_base:
  errbit_api_key:
  dropbox_api_key:
  dropbox_api_secret:
  dropbox_extended_api_key:
  dropbox_extended_api_secret:
  dropbox_extended_access_token:

development:
  <<: *defaults
  secret_key_base: 9a5222f8e7fccc168ae21b910603088471321729da3f3b860c8e5f20a2d9d3ea84c0014c5dd4be3216cdd1c932062c63e88ff5679dae6fd19fa829c22ddf9676

test:
  <<: *defaults
  secret_key_base: 28d4c32a3327ddd676600343c401377602cfc4fbc8e883d7799958a7f08153c23c38dd55661ef21d6ae650a440ea499c84e47f10b3a81fa5485da4dfdadae4fd

staging:
  <<: *defaults

production:
  <<: *defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  errbit_api_key: <%= ENV["ERRBIT_API_KEY"] %>
