
# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
---
:verbose: false
:concurrency: 10

# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 30

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - [pre_assignments_delivery, 7]
  - [remote_file_delivery, 6]
  - [grouping_delivery, 9]
  - [process_and_deliver_grouped, 9]
  - [process_fiduceo_operations, 5]
  - [retrieve_fiduceo_operations, 5]
  - [retrieve_fiduceo_documents, 5]
  - [retrieve_from_grouping, 9]
  - [retrieve_preseizures, 9]
  - [sync_remote_files, 6]
  - [dematbox, 9]
  - [default, 1]
  - [mailers, 1]

# you can override concurrency based on environment
production:
  :concurrency: 12
staging:
  :concurrency: 15