---
# The authentication token for the application.
authentication: QfwXry--1pgK7HY3fAqMBSORcCXaUW7ehDoWRLvVzDc
# Temporarily ignore those endpoints to limit usage
ignored_endpoints:
  - Account::RetrieversController#index
  - Admin::AdminController#reports_delivery
  - Admin::AdminController#ocr_needed_temp_packs
  - Admin::AdminController#processing_temp_packs
  - Admin::AdminController#failed_packs_delivery
  - Admin::AdminController#failed_reports_delivery
  - Admin::AdminController#blocked_pre_assignments
  - Admin::AdminController#bundle_needed_temp_packs
  - Admin::AdminController#awaiting_pre_assignments
  - Admin::AdminController#currently_being_delivered_packs
  - Account::RetrieversController#index
  - Account::Organization::RetrieversController#index
