#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development:         &development_defaults
  key:               1234567890ABCDEF1234567890ABCDEF
  iv:                1234567890ABCDEF
  cipher_name:       aes-128-cbc
  encoding:          :base64strict
  always_add_header: true

test:
  <<: *development_defaults

staging:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEA0in0CKbgS0ryBap1Jn2iuMVn/waIE+ZBlXmGa7OOOepOKXxG
    do5suGpfU64bqw8ux6RHDPU5y1PU5r+k0W8oBrL39VRbf+a/PXXbFh05J4x3JAfA
    zOgyNdxVh8z4ilcriL2jY4K2hm8MCvi4JN0ivO0QFoUH/k4pb5tTtub2NgvXjXvS
    sAGKJeXz6pT90nWl3nAe/ywrG1OWMw1v+rydWndDHpaut3WCF1CmDWrALYRqG03J
    +QZCP8BTP+Pgt3KFslJJ9nj9Y1Sz4GxyD6AhVRYSzDd6zxmxWg5L6jD8Xq6/Q9Ue
    rPHNSRLfZhgGMLyPx9yHaydjrK9yG3CSxY0bRQIDAQABAoIBAQCR2S2S54RWnC8z
    gWUFjkDj65NNZ5H+BVhUTF7d1WEJjjIqFiWsVxDaNm/rWbO31bSINdhdBL3T/lyM
    uki+U166r27m4WESdOcY1vZw9VzZtmBkL8E8MpPNzxfIQ5XkI7SBk+GUyHy09NGt
    t4fLhW97HyWAC1hNwp585pWFI+mP/QvqBgC4GTygyfSVSUMVqYsjwyUCLk8s9PZZ
    13oszcG2HHdrubTI0LIFVqwh83yZtPqgt9S72gI/CsFOaZey3MmmC8GBNtH48y+f
    4vcVdjIvBpnrWp5zeJFerhMjX/qJyTl2N6jNadKrHGsWIbv2G20QXZ/XT7GUlVeE
    RUQ86FRtAoGBAOlpsGdzBIXAEHLUplnHSKTkTW/zp0sCzFbXb5zorPqQqXGxXBwR
    VY3yRe1A8UF7sf5fyY5+W8GlAq8mqgwZFRKTjZSs8G6OBmgWWSJHGA6jQDplVmPh
    jL44Wz7RkEnSuzvs4thqgYB3sMKS2jPGtgbsAUxmm3Prx+5xxZmNQpE7AoGBAOaA
    Ue4SXL2lA11wBsNve1Qg5h63kJkWhKDe+ZnKg8atg1SGMnWAHfH15y3wspQMhRvB
    clYJipey5jX9DgEyD116it6yq6hZeoja37UqXlI2rKeVjiPhDgGKLtPsN2gyvL6B
    nIa/Vid4wLxoW9Ee1biqLGJiqsnGZI5ML+6wBD1/AoGBAMqLgh5i+putzRg4W5ow
    imM8Ec6CGrvG09bP3/TDG8fa3I7iH1Hj4N/qSq/U2QW/9vcL2/WgxLLHJAslfA4/
    fb++9u77GzB0Yi7UpchO9RtOop+J7GuEAAPZF6TtaU4GZZ9csoSl93apZmOR13Ny
    jeZ3ybCooWD4S2gophXXNNqdAoGBAMphxI3ppXAFoIy7vdR+36QgNqyls9oWQWEW
    JcV4YHdjBbqDEW7FjIVTySU2/zSqQXz7Pq54Ni23sBWbGF7IW2FSJPgfnER2O/ZJ
    Zr4kcyhwROvnjiPGiIuljjQYZRWh5sLF/m75NGX3yhIi9usHzdMT52CDDT2YadXe
    4v8JoM91AoGANFp3gkVvggbVDw925zJvrsRxgSZvHQQ/FoqmzRMFAEMqHDiYe/VI
    mZ0elv15DV/JUNIO2rHfdDLRlovUDl3b3FwbJXHp2I9L9X8NTBcBY1L+nZKVkKud
    R06It0KHEKyJ2kKEl2W9qO+23mrfg7kW17WogtiQz7s4db7i1wxBdzU=
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename:      /data/idocus/deploy/staging/shared/keys/idocus_staging.key
      iv_filename:       /data/idocus/deploy/staging/shared/keys/idocus_staging.iv
      cipher_name:       aes-256-cbc
      encoding:          :base64strict
      version:           1
      always_add_header: true

production:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEA7HKhvksLPvTFC8NAYsvTBNY5hNPlNDakp511h3WjKQy1VWpq
    tLp6rT9OC6BCpcBVnvShV2VzeBJz7wOCaAlRy3lCT69FKozebw8nXy2A5FgxtiNC
    DBQG6oi8yjqqDin3b/vEgCWxRjNUCCBLRULlBvql6Yjpckuh2+OHb4ZABYLSocX2
    YkrnL6JOr9APuzy+fi9IS6C+skiP7IKY2wlQ0nLIGxXBNq9J1UkuKMQcogKSAWs3
    z9+e/H3Vqq8HxW3ZrqTQ2LkXcDCj/wEZUGE0vqWXlvyX42rjSlzuHml1nsfZuQCy
    XL7iRcPU+BTQkuU+QQ3as91hYQaCHhXla9+kBwIDAQABAoIBAD3MhDvBT3In9Wxq
    nuRzk3a7KxNtcoWgFo78l6BM/dUXzjlB9BvCdZfcaOCfBWxfBcHi/FxkVra2U/jP
    eQEKFofQ7KT5EWHaqbRrSIYW1Y5ZAr0xH+0aOuiHzpgolxPWoiZxrl0z/M51UexB
    zIqQvl2Bm2WbdDB8VhSrtlVOyGLn2smayNM2OnluS8WEDJL7bC7nV5jeDeoZiR+3
    EM/dReKx3pGBw4L5I8mjEFVb5VNY34fSJdX8ZgKggEFe5NBDk7PoX9rqoJZ7yYcs
    P5X+QiGHPsSTYsFps7b7ozOZlpkfIozXQe03EErB4qBRq/jTA3CM5S2YtS+9nsyk
    AYf2gLECgYEA/le5mPOUnG4qhHHTpLnD8KjKfkQh0PZ6E6ADcfFPHRwTMepdKf3H
    wy3oaiZmk+sCCWZBRxuSXBAOH+6cvJkmf/OGPukpNyZB4e/xWO/qB6j8jxqxwvdi
    uTRKjoxPyf1ZxTPsxSssIo6wB0bm1xbD7E4YKhFioz/1bNSXY0872ykCgYEA7f0O
    UP94+cWJWQxihhJJGIafny16MbfPNusf3fr87+AqF9YOpWjPRe22nNDoVjnBrM74
    LVnNxu+ghfxow9rV1zDA7PbGADm56S/AIDusGJFXyRMmJpY1X1OU8tqtqC66WfyK
    FqUpRYJY58TQO4lEc+0vkAvcfStxFZyrFn2Lm68CgYEA4kelxaAfvTR9+ytRwiHL
    YxaoYMG43DIM1dzsc7jeS+WoZiY+EJfJ26nCNn5HkJ3qR/aDaQHsqp9WEa62H0yZ
    5ggAjYPeuUP+JUbVj+ySZ5I+cAqtz+lMGb2d/0hxzCDsdvgFVD1enLgZf7/iq8WD
    NX8dHIAvI1JJxTM2JJJfjFECgYAHnIBItuL3mgm6f1rnTs5nqmaQgLPXwzktWHe8
    cbqFMXYnLQFq6N84LVIZ0dScbVx0Wmo1iRm7sw4/OsNfADC2oSiKa5oJh88aVhye
    60mlv4A/Pg2KTmOGmPW6jqPfLR9ooVsJPl8Dihet0e2W+dzmmD9dLAPxPOJw/oG6
    RmmgoQKBgQDAUUMsYqe+Xv5VOCLeEOgoo9SPm7Iu077ney2cQq7otBo0tJa0lanT
    z25BhvoOKROkBtLFTzCyLK8sJqYatJGi1u+Wg9n7Tzp7K9CRqRr15/pDhkXmUuH3
    YJhXg9JQLHiuidkyOjaCbtpgjcMDOU3VGZ2GiQfjuJJUJ0jJkNmcag==
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename:      /data/idocus/deploy/production/shared/keys/idocus_production.key
      iv_filename:       /data/idocus/deploy/production/shared/keys/idocus_production.iv
      cipher_name:       aes-256-cbc
      encoding:          :base64strict
      version:           1
      always_add_header: true
